brain_two/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("todo_list_list")),
        name="home",
    ),
    path("todos/", include("todos.urls")),
]

todos/urls.py
from django.urls import path

from todos.views import (
    TodoItemCreateView,
    TodoItemUpdateView,
    TodoListCreateView,
    TodoListDeleteView,
    TodoListListView,
    TodoListDetailView,
    TodoListUpdateView,
)


urlpatterns = [
    path("", TodoListListView.as_view(), name="todo_list_list"),
    path("<int:pk>/", TodoListDetailView.as_view(), name="todo_list_detail"),
    path("create/", TodoListCreateView.as_view(), name="todo_list_create"),
    path(
        "<int:pk>/edit/", TodoListUpdateView.as_view(), name="todo_list_update"
    ),
    path(
        "<int:pk>/delete/",
        TodoListDeleteView.as_view(),
        name="todo_list_delete",
    ),
    path(
        "items/create/", TodoItemCreateView.as_view(), name="todo_item_create"
    ),
    path(
        "items/<int:pk>/edit/",
        TodoItemUpdateView.as_view(),
        name="todo_item_update",
    ),
]

todos/models.py
from django.db import models


class TodoList(models.Model):
    name = models.CharField(max_length=100)
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class TodoItem(models.Model):
    task = models.CharField(max_length=100)
    due_date = models.DateTimeField(blank=True, null=True)
    is_completed = models.BooleanField(default=False)
    list = models.ForeignKey(
        "TodoList", related_name="items", on_delete=models.CASCADE
    )

    def __str__(self):
        return self.task

todos/forms.py
from django import forms
from todos.models import TodoList


class TodoListForm(forms.ModelForm):
    class Meta:
        model = TodoList
        fields = ["name"]

todos/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from todos.models import TodoList, TodoItem


class TodoListListView(ListView):
    model = TodoList
    template_name = "todos/list.html"


class TodoListDetailView(DetailView):
    model = TodoList
    template_name = "todos/detail.html"


class TodoListCreateView(CreateView):
    model = TodoList
    template_name = "todos/new.html"
    fields = ["name"]
    success_url = reverse_lazy("todo_list_detail")

    def get_success_url(self):
        return reverse_lazy("todo_list_detail", args=[self.object.id])


class TodoListUpdateView(UpdateView):
    model = TodoList
    template_name = "todos/edit.html"
    fields = ["name"]

    def get_success_url(self):
        return reverse_lazy("todo_list_detail", args=[self.object.id])


class TodoListDeleteView(DeleteView):
    model = TodoList
    template_name = "todos/delete.html"
    success_url = reverse_lazy("todo_list_list")


class TodoItemCreateView(CreateView):
    model = TodoItem
    template_name = "todos/new_item.html"
    fields = ["task", "due_date", "is_completed", "list"]

    def get_success_url(self):
        return reverse_lazy("todo_list_detail", args=[self.object.list.id])


class TodoItemUpdateView(UpdateView):
    model = TodoItem
    template_name = "todos/edit_item.html"
    fields = ["task", "due_date", "is_completed", "list"]

    def get_success_url(self):
        return reverse_lazy("todo_list_detail", args=[self.object.list.id])

todos/templates/todos/delete.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title></title>
  </head>
  <body>
    <main>
      <div>
        <h1>Are you sure?</h1>
        <form method="POST">
          {% csrf_token %}
          <!---->
          {{ form.as_p }}
          <div>
            <button>Delete</button>
          </div>
        </form>
      </div>
    </main>
  </body>
</html>

todos/templates/todos/detail.html
<!DOCTYPE html>
<html>
  <head>
    <title>To Do</title>
  </head>
  <body>
    <main>
      <div>
        <h1>{{ todolist.name }}</h1>
        <p>
          <a href="{% url 'todo_list_update' todolist.pk %}">Edit</a>
        </p>
        <p>
          <a href="{% url 'todo_list_delete' todolist.pk %}">Delete</a>
        </p>
        <h2>Tasks</h2>
      </div>
      <div>
        <table>
          <thead>
            <tr>
              <th>Task</th>
              <th>Due Date</th>
            </tr>
            <tbody>
              {% for item in todolist.items.all %}
              <tr>
                  <td>
                    <a href="{% url 'todo_item_update' item.pk %}">{{ item.task }}</a>
                  </td>
                  <td>{{ item.due_date}}</td>
              </tr>
              {% endfor %}
            </tbody>
          </thead>
        </table>
      </div>
    </main>
  </body>
</html>

todos/templates/todos/edit.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title></title>
  </head>
  <body>
    <main>
      <div>
        <h1>Update List</h1>
        <form method="POST">
          {% csrf_token %}
          <!---->
          {{ form.as_p }}
          <div>
            <button>Update</button>
          </div>
        </form>
      </div>
    </main>
  </body>
</html>

todos/templates/todos/edit_item.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title></title>
  </head>
  <body>
    <main>
      <div>
        <h1>Update Item</h1>
        <form method="POST">
          {% csrf_token %}
          <!---->
          {{ form.as_p }}
          <div>
            <button>Update</button>
          </div>
        </form>
      </div>
    </main>
  </body>
</html>

todos/templates/todos/list.html
<!DOCTYPE html>
<html>
  <head>
    <title>To Do</title>
  </head>
  <body>
    <main>
      <div>
        <h1>My Lists</h1>
        <p>
          <a href="{% url "todo_list_create" %}">Create a New List</a>
        </p>
        <p>
          <a href="{% url 'todo_item_create' %}">Create a New Item</a>
        </p>
        <table>
          <thead>
            <tr>
              <th>Name</th>
              <th>Number of Items</th>
            </tr>
            <tbody>
              {% for list in todolist_list %}
              <tr>
                  <td><a href="{% url "todo_list_detail" list.pk %}">{{ list.name }}</td>
                    <td>{{ list.items.count }}</td>
              </tr>
              {% endfor %}
            </tbody>
          </thead>
        </table>
      </div>
    </main>
  </body>
</html>

todos/templates/todos/new.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title></title>
  </head>
  <body>
    <main>
      <div>
        <h1>Create a New List</h1>
        <form method="POST">
          {% csrf_token %}
          <!---->
          {{ form.as_p }}
          <div>
            <button>Create</button>
          </div>
        </form>
      </div>
    </main>
  </body>
</html>

todos/templates/todos/new_item.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title></title>
  </head>
  <body>
    <main>
      <div>
        <h1>Create a New Item</h1>
        <form method="POST">
          {% csrf_token %}
          <!---->
          {{ form.as_p }}
          <div>
            <button>Create</button>
          </div>
        </form>
      </div>
    </main>
  </body>
</html>